services:
    test:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        image: burst-builder:dev
        command: ["cargo", "test", "--workspace"]

    controller:
        build:
            context: .
            dockerfile: Dockerfile
        image: burst-runtime:dev
        command:
            [
                "/usr/local/bin/burst-controller",
                "--config",
                "/app/burst-config/burst.config.json",
            ]
        ports:
            - "50051:50051"

    client:
        build:
            context: .
            dockerfile: Dockerfile
        image: burst-runtime:dev
        entrypoint: ["/usr/local/bin/burst-client"]
        command: ["--config", "/app/burst-config/burst.config.json"]
        depends_on:
            - controller

    worker:
        image: burst-runtime:dev
        entrypoint: ["/usr/local/bin/burst-worker"]
        command: ["--config", "/app/burst-config/burst.config.json"]
        depends_on:
            - controller
            - client

volumes:
    steal-output:
