syntax = "proto3";

package burst.v1;
import "burst/v1/job.proto";
import "burst/v1/worker.proto";

service ControllerRpc {
  rpc SubmitJob(SubmitJobRequest) returns (SubmitJobResponse);
  rpc GetJobStatus(GetJobStatusRequest) returns (GetJobStatusResponse);
  rpc RegisterWorker(RegisterWorkerRequest) returns (RegisterWorkerResponse);
  rpc PollJob(PollJobRequest) returns (PollJobResponse);
  rpc ReportJobResult(ReportJobResultRequest) returns (ReportJobResultResponse);
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
}
